name: Nuget Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: version
        required: true
        type: string
        
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      - name: restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
