
name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: version
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      - name: restore dependencies
        run: dotnet restore

      - name: build
        run: dotnet build -c Release --no-restore

      - name: publish to local
        run: dotnet publish src/DotFastLZ.Packaging.Tools -c Release --no-restore --no-self-contained --output working-temp

      - name: Zip
        run: |
          cd working-temp
          echo "dotnet DotFastLZ.Packaging.Tools.dll" > run.bat
          zip -r ../DotFastLZ.Packaging.Tools-${{ github.event.inputs.version }}.zip ./
        if: success()

      - uses: release-drafter/release-drafter@master
        with:
          version: ${{ github.event.inputs.version }}
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: zip Upload
        uses: softprops/action-gh-release@v1
        with:
          files: |
            DotFastLZ.Packaging.Tools-${{ github.event.inputs.version }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: force update version tag
        run: |
          git tag ${{ github.event.inputs.version }}
          git push origin refs/tags/${{ github.event.inputs.version }} -f
        
